# Generated by Django 4.0.1 on 2022-02-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_artista_galeria_alter_artista_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='galeriaALaQueLeCompro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='galeriaEnQueCompro',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Galería en la adquirió la obra'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='artistaAlQueLeCompro',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Autor de la obra'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='nombre y apellido'),
        ),
    ]
